[project]
name = "dialog-context-bot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.23.0",
    "aiolimiter>=1.2.1",
    "httpx>=0.28.1",
    "openai>=2.11.0",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff==0.14.9",
]
